import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import { Playfair_Display, DM_Sans } from "next/font/google";

const playfair = Playfair_Display({
	subsets: ["latin"],
	variable: "--font-playfair",
	display: "swap",
});

const dmSans = DM_Sans({
	subsets: ["latin"],
	variable: "--font-dmsans",
	display: "swap",
});

export const metadata: Metadata = {
	title: "NextJS Web Builder",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="cs" suppressHydrationWarning>
			<body className={`${playfair.variable} ${dmSans.variable} antialiased`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
